"""oidc user fields

Revision ID: 629212e1389d
Revises: 21e974cdb708
Create Date: 2026-09-13 20:20:20.483003
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '629212e1389d'
down_revision: str | None = '21e974cdb708'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oidc_sub', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_oidc_sub'), ['oidc_sub'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_oidc_sub'))
        batch_op.drop_column('email')
        batch_op.drop_column('oidc_sub')

    # ### end Alembic commands ###
