"""telegram notifications

Revision ID: 1845842e4608
Revises: 629212e1389d
Create Date: 2026-09-13 20:47:59.147591
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '1845842e4608'
down_revision: str | None = '629212e1389d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminded_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_chat_id', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('telegram_chat_id')

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_column('reminded_at')

    # ### end Alembic commands ###
