"""link telegram to account

Revision ID: 8c78c2cadb34
Revises: 1845842e4608
Create Date: 2026-09-13 22:26:53.803063
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '8c78c2cadb34'
down_revision: str | None = '1845842e4608'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_login_token_link_user', 'users', ['link_user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_tokens', schema=None) as batch_op:
        batch_op.drop_constraint('fk_login_token_link_user', type_='foreignkey')
        batch_op.drop_column('link_user_id')

    # ### end Alembic commands ###
