"""merge events into assignments

Revision ID: 3830f69ca7f1
Revises: 8c78c2cadb34
Create Date: 2026-09-13 23:21:59.891974
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '3830f69ca7f1'
down_revision: str | None = '8c78c2cadb34'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('hard_deadline', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('points_per_problem', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('full_clear_bonus', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('full_clear_bonus')
        batch_op.drop_column('points_per_problem')
        batch_op.drop_column('hard_deadline')
        batch_op.drop_column('description')

    op.create_table('events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('problem_set_id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.Column('starts_at', sa.DATETIME(), nullable=False),
    sa.Column('ends_at', sa.DATETIME(), nullable=False),
    sa.Column('points_per_problem', sa.FLOAT(), nullable=False),
    sa.Column('full_clear_bonus', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problem_set_id'], ['problem_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
